server:
  port: 1113

keycloak:
  realm: formation-ms
  auth-server-url: http://localhost:8080/auth
  resource: sales-app
  credentials:
    secret: Ng03JhfkRQEAOS5R86lJqPVTlOkXegPg
  principal-attribute: preferred_username
  bearer-only: true

spring:
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: sales-service
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/sales_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

